name: Wake Streamlit App

on:
  schedule:
    - cron: '0 */4 * * *'
  workflow_dispatch:

jobs:
  wake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v4

      - name: Instala Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Instala dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Roda o script
        run: python wake_streamlit.py
